
---
Standards:
  - Title: Js Week 1
    Description: Js Week 1
    UID: c98d17d95358299af09b0b276d67a3e6
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 6417cc03-a1be-4e53-9886-ca4559062e3c
        Path: /01-js-week-1/setup-linting.md      
      -
        Type: Lesson
        UID: edc83d0b-ad22-4af0-b699-7cd91c348217
        Path: /01-js-week-1/ruby-to-js-worksheet.md
      -
        Type: Lesson
        UID: 348dbcad-93f3-49e3-8aeb-f314c91096ad
        Path: /01-js-week-1/welcome-to-second-language.md
      - 
        Type: Lesson
        UID: 2a04d88b-f4c9-41eb-be33-6ed68350f222
        Path: /01-js-week-1/js-intro.md
      -
        Type: Lesson
        UID: ead12e11-67b9-43c1-b3f2-dd0355c63e47
        Path: /01-js-week-1/variables-conditionals-iteration.md
      -
        Type: Lesson
        UID: 01fc3ca7-2c2e-4201-8b86-14438d8f1a77
        Path: /01-js-week-1/functions-intro.md
      - 
        Type: Lesson
        UID: c95a8cd5-e90f-42aa-a457-e4162b4f581f
        Path: /01-js-week-1/first-class-functions.md
      - 
        Type: Lesson
        UID: 49699f80-f8a7-42ee-a219-db847433ff4f
        Path: /01-js-week-1/anonymous-and-foreach-loops.md
      - 
        Type: Lesson
        UID: 14d14768-4767-48c1-bf20-88fd3e2bfb3b
        Path: /01-js-week-1/functions-worksheet.md        
      -
        Type: Lesson
        UID: e655b165-aeca-49a5-8084-2f2dda7f9a14
        Path: /01-js-week-1/js-calculator.md 
      -
        Type: Lesson
        UID: 384292d5-0b40-40bd-a836-e53a8bdbfab1
        Path: /01-js-week-1/arrow-functions.md
      -
        Type: Lesson
        UID: ad3ac1f7-9eca-4902-a0c6-9e3afd386915
        Path: /01-js-week-1/arrow-functions-anonymous-this.md
      -
        Type: Lesson
        UID: f0d68e28-4087-4d4a-bf4f-b5d91e02496d
        Path:  /01-js-week-1/js-testing.md
      -
        Type: Lesson
        UID: 9a100534-5471-492e-bc53-46ce1b6407b1
        Path: /01-js-week-1/closures-intro.md
      -
        Type: Lesson
        UID: 58b6fb48-4f6a-42d4-977e-31622958bd8b
        Path: /01-js-week-1/classes.md
      -
        Type: Resource
        UID: c30ff33d-a8f0-4df6-8ac2-471dd884d44f
        Path: /01-js-week-1/examples/eslintrc.examples.resource.md
      - 
        Type: Lesson
        UID: 082bbea3-d5eb-4406-98fb-d0b8b8e341f7
        Path: /01-js-week-1/closures-continued.md
      -
        Type: Checkpoint
        UID: 0ae815cf-1c7d-490f-9f80-5d33fb7a4007
        Path: /01-js-week-1/js-adagrams.checkpoint.md
  - 
    Title: Js Week 2
    Description: Async Api Calls and Intro to ReactJS
    UID: 1dd08b18-ea6d-4e07-a58a-04a72950c011
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 8c72d947-2141-4448-b08e-f70aecafe1ef
        Path: /02-js-week-2/async-intro.md
